apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democrm
  namespace: argocd
spec:
  project: democrm
  source:
    repoURL: http://35.178.81.143/piaseckip/gitops.git
    targetRevision: HEAD
    path: democrm
  destination:
    server: https://kubernetes.default.svc
    namespace: default