apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert 
  namespace: default 
spec:
  dnsNames:
    - piotrek-crm.ddns.net
  secretName: example-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer