apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-mngr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cert-manager-v1.10.0
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook