apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-inogress-ctrl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nginx-ingress-0.15.1
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook